name: Tag release

on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "CI version bump to {{version}}"
          tag-prefix: "v"
          version-type: "minor"
